version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    hostname: wordcloud
    container_name: wordcloud
    volumes:
      - ./:/go/src/github.com/bushiyama/wordcloud
    working_dir: /go/src/github.com/bushiyama/wordcloud
    environment:
      - GOPATH=/go
    ports:
      - "8080:8080"
